# Generated by Django 5.0.3 on 2024-03-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0005_mang_sona1_varv_mang_sona2_varv_mang_sona3_varv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mang',
            name='mitmes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
