# Generated by Django 5.0.3 on 2024-03-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0006_mang_mitmes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mang',
            name='mitmes',
            field=models.IntegerField(default=1),
        ),
    ]
